#!/usr/bin/env python

import sys
import re

def check_pattern(heading, pattern):
    if len(heading) >= 51: 
        return False

    match = re.match(pattern, heading)

    return match != None
    

def main(args=None):
    with open(args, 'r') as file:
        first_line = file.readline()
        pattern = r'^(fix|ref) #[0-9]+: [A-Z].+[\n]$'

        if check_pattern(first_line, pattern):
            sys.exit(0)

        print("Commit aborted, please use the specified heading format: ")
        print("Format: " + pattern)
        print("Length: " + str(50))
        print("Your Length: " + str(len(first_line)) + "\n")
        print("Your message: ")

        file.seek(0)
        for line in file:
            if not line.startswith("#"):
                sys.stdout.write(line)

        sys.exit(1)

if __name__ == "__main__":
  args = sys.argv[1]
  main(args)
